In [ ]:
import pandas as pd
import numpy as np
import sympy as sp
#from sympy import * 
import random
import matplotlib.pyplot as plt
import matplotlib.cm as cm
plt.style.use('seaborn-whitegrid')
%matplotlib inline

In [ ]:
A = sp.Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]]) # symbolic matrix
B = np.array([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]]) # numpy 2D-array
print(type(A))
print(type(B))
print(A)
print(B)

<class 'sympy.matrices.dense.MutableDenseMatrix'>
<class 'numpy.ndarray'>
Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]])
[[ 1  0  1  3]
 [ 2  3  4  7]
 [-1 -3 -3 -4]]


In [ ]:
A.rref()

(Matrix([
 [1, 0,   1,   3],
 [0, 1, 2/3, 1/3],
 [0, 0,   0,   0]]), (0, 1))

In [ ]:
# Augmented matrix with nonzero right hand side
A = sp.Matrix([[1,2,-1,-1,1], [2,4,-2,3,3], [-1,1,-2,4,2]])
print(A.rref()) # returns the rref and the pivot column indices as a tuple
# x1, x2, and x4 are the pivot variables. The remaining variable(s) x3 is a free variable.
# x1+x3 = -2/5 -> x1 = -x3 -(2/5)
# x2-x3 = 4/5 -> x2 = x3+(4/5) 
# x4 = 1/5
# Augmented matrix with zero right hand side
A_withzerorhs = sp.Matrix([[1,2,-1,-1,0], [2,4,-2,3,0], [-1,1,-2,4,0]])
print(A_withzerorhs.rref())

(Matrix([
[1, 0,  1, 0, -2/5],
[0, 1, -1, 0,  4/5],
[0, 0,  0, 1,  1/5]]), (0, 1, 3))
(Matrix([
[1, 0,  1, 0, 0],
[0, 1, -1, 0, 0],
[0, 0,  0, 1, 0]]), (0, 1, 3))


In [ ]:
# A system with no solutions
A = sp.Matrix([[1, 2, 3, 6], [2, 4, 6, 13]]) # an augmented matrix corresponding to
# x1+2*x2+3*x3 = 6 and 2*x1+4*x2+6*x3 = 13
print(A.rref())
# x1 is the pivot variable, x2 and x3 are the free variables
# x1+2*x2+3*x3 = 0
# 0 = 1 (not possible)

(Matrix([
[1, 2, 3, 0],
[0, 0, 0, 1]]), (0, 3))
